<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {

        ###======== CREATION DES USERS PAR DEFAUT==========###
        $users = [
            [
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'admin@gmail.com',
                'password' => '$2y$10$CI5P59ICr/HOihqlnYUrLeKwCajgMKd34HB66.JsJBrIOQY9fazrG', #admin
                'is_super_admin' => true,
                'phone' => "22961765591",
            ],
            [
                'name' => 'Joel PPJ',
                'username' => 'ppjjoel',
                'email' => 'ppjjoel@gmail.com',
                'password' => '$2y$10$ZT2msbcfYEUWGUucpnrHwekWMBDe1H0zGrvB.pzQGpepF8zoaGIMC', #ppjjoel
                'is_super_admin' => true,
                'phone' => "22961765592",
            ]
        ];

        foreach ($users as $user) {
            \App\Models\User::factory()->create($user);
        }

        ###========CREATION DES TYPES DE TICKETS PAR DEFAUT ==========###
        $ticket_types = [
            [
                'name' => 'Issue',
            ],
            [
                'name' => 'Question',
            ]
        ];

        foreach ($ticket_types as $ticket_type) {
            \App\Models\TicketType::factory()->create($ticket_type);
        }

        ###========CREATION DES STATUS DE TICKETS PAR DEFAUT ==========###
        $ticket_status = [
            [
                'name' => 'Nouveau',
            ],
            [
                'name' => 'En Cour',
            ],
            [
                'name' => 'Suspendu',
            ],
            [
                'name' => 'Fini',
            ],
        ];

        foreach ($ticket_status as $status) {
            \App\Models\TicketStatus::factory()->create($status);
        }

        #======== CREATION DES CATEGORIES DE PRODUIT PAR DEFAUT =========#
        $product_categories = [
            [
                "name" => "Tout",
                "description" => "Toutes catégorie confondues",
            ],
            [
                "name" => "Tout/Dépenses",
                "description" => "Catégorie dépense",
            ],
            [
                "name" => "Tout/Vendable",
                "description" => "Produit Vendable",
            ],
            [
                "name" => "Tout/Vendable/POS",
                "description" => "Produit Vendable Point de Vente",
            ]
        ];
        foreach ($product_categories as $product_categorie) {
            \App\Models\ProductCategory::factory()->create($product_categorie);
        }

        #======== CREATION DES TYPES DE PRODUIT PAR DEFAUT =========#
        $produitTypes = [
            [
                "name" => "Produit stockable",
                "description" => "Un produit stockable est un produit dont on peut gérer le stock!",
            ],
            [
                "name" => "Service",
                "description" => "Un service est un produit immatériel que vous fournissez!",
            ],
            [
                "name" => "Consommable",
                "description" => "Un produit consommable est un produit dont le stock n'est pas géré!",
            ],
        ];
        foreach ($produitTypes as $type) {
            \App\Models\ProductType::factory()->create($type);
        }

        #======== CREATION DES ETIQUETTES DE PRODUIT PAR DEFAUT =========#
        $produitEtiquettes = [
            [
                "name" => "Etiquette 1",
            ],
            [
                "name" => "Etiquette 2",
            ],
            [
                "name" => "Etiquette 3",
            ],
        ];
        foreach ($produitEtiquettes as $produitEtiquette) {
            \App\Models\Etiquette::factory()->create($produitEtiquette);
        }

        ##======== CREATION DES ROLES PAR DEFAUT ============####
        $roles = [
            [
                'label' => 'is_marketer'
            ],
            [
                'label' => 'is_exploitation'
            ],
            [
                'label' => 'is_logistique'
            ]
        ];
        foreach ($roles as $role) {
            \App\Models\Role::factory()->create($role);
        };

        ##======== CREATION DES REPERTOIRES PAR DEFAUT ============####
        $repertoires = [
            [
                'firstname' => 'AJAYI',
                'lastname' => 'Benoît',
                'ministry' => 'Pasteur',
                'denomination' => 'Eglise Centre de Prière des Apôtres (CPA)',
                'residence' => "Djeffa PK 16",
                "commune" => "Sèmè Kpodji",
                "contact" => "67529154",
                "owner" => 1,
            ],
            [
                'firstname' => 'ABIDOHO',
                'lastname' => 'Johane',
                'ministry' => 'Pasteur',
                'denomination' => 'MPRSEC',
                'residence' => "Cotonou",
                "commune" => "Cotonou",
                "contact" => "69446087",
                "owner" => 1,
            ],
            [
                'firstname' => 'ADINGBANNON',
                'lastname' => 'Flora',
                'ministry' => 'Prophétesse',
                'denomination' => 'ECPA',
                'residence' => "Djeffa",
                "commune" => "Sèmè Kpodji",
                "contact" => "67197233",
                "owner" => 1,
            ],
            [
                'firstname' => 'AKPAMOLI',
                'lastname' => 'Richard',
                'denomination' => 'Eglise Biblique du Fondement Chrétien (EBFC',
                'residence' => "PK 10",
                'ministry' => 'Sèmè Kpodji',
                "commune" => "Sèmè Kpodji",
                "contact" => "66020409",
                "owner" => 1,
            ],
            [
                'firstname' => 'HOUNGA',
                'lastname' => 'Innocent',
                'ministry' => 'Evangéliste',
                'denomination' => 'MIERS Chandelier d’or',
                'residence' => "Djèrègbé",
                "commune" => "Sèmè Kpodji",
                "contact" => "96074226",
                "owner" => 1,
            ],
            [
                'firstname' => 'AHOUANDJINO',
                'lastname' => 'U Henri',
                'ministry' => 'Apôtres',
                'denomination' => 'Mission Internationale Cité de Triomphe',
                'residence' => "Sèmè Kpodji",
                "commune" => "Sèmè Kpodji",
                "contact" => "97879047",
                "owner" => 1,
            ],
            [
                'firstname' => 'TOHOUEGNON',
                'lastname' => 'Martin',
                'ministry' => 'Pasteur',
                'denomination' => 'Eglise en Mission pour la Moisson des Ames (EMMA)',
                'residence' => "Makinsa",
                "commune" => "Abomey Calavi",
                "contact" => "94864161",
                "owner" => 1,
            ],
            [
                'firstname' => 'BONOU',
                'lastname' => 'Martin',
                'ministry' => 'Pasteur Fondateur',
                'denomination' => 'Eglise Montagne Union des Saints Divin (ESMUD)',
                'residence' => "Zounta",
                "commune" => "Dangbo",
                "contact" => "97155536",
                "owner" => 1,
            ],
            [
                'firstname' => 'SAGBOHAN',
                'lastname' => 'Fabrice',
                'ministry' => 'Pasteur',
                'denomination' => 'MEAD',
                'residence' => "Missérété",
                "commune" => "AkproMissérété",
                "contact" => "97229653",
                "owner" => 1,
            ],
            [
                'firstname' => 'AZANDEGBE',
                'lastname' => 'Wilfried',
                'ministry' => 'Pasteur',
                'denomination' => 'MEDiC Bénin',
                'residence' => "Cocotomey",
                "commune" => "Abomey Calavi",
                "contact" => "96884488",
                "owner" => 1,
            ],
            [
                'firstname' => 'HOUESSOU',
                'lastname' => 'Marcel B.',
                'ministry' => 'Evangéliste',
                'denomination' => 'EBSE',
                'residence' => "Akpakpa",
                "commune" => "Cotonou",
                "contact" => "97628156",
                "owner" => 1,
            ],
            [
                'firstname' => 'AGBANDE',
                'lastname' => 'Mathurin Sèvèho',
                'ministry' => 'Pasteur',
                'denomination' => "EPED",
                'residence' => "Porto Novo",
                "commune" => "Porto Novo",
                "contact" => "96549212",
                "owner" => 1,
            ],
            [
                'firstname' => 'DOSSA',
                'lastname' => 'Mathias',
                'ministry' => 'Evangéliste',
                'denomination' => "CAC",
                'residence' => "Tatonnonk on",
                "commune" => "Adja-Ouèrè",
                "contact" => "97233813",
                "owner" => 1,
            ],
            [
                'firstname' => 'DOSSA',
                'lastname' => 'Toussaint',
                'ministry' => 'Accueil',
                'denomination' => "CAC",
                'residence' => "Tatonnonk on",
                "commune" => "Adja-Ouèrè",
                "contact" => "90151847",
                "owner" => 1,
            ],
            [
                'firstname' => 'Hossou',
                'lastname' => 'Christophe',
                'ministry' => 'Choriste',
                'denomination' => "CAC",
                'residence' => "Tatonnonk on",
                "commune" => "Adja-Ouèrè",
                "contact" => "53667288",
                "owner" => 1,
            ],
            [
                'firstname' => 'ABIKO',
                'lastname' => 'Marcellin',
                'ministry' => 'Evangéliste',
                'denomination' => "MEGA",
                'residence' => "Bonou",
                "commune" => "Bonou",
                "contact" => "66478001",
                "owner" => 1,
            ],
            [
                'firstname' => 'LAWANI',
                'lastname' => 'Sahadou',
                'ministry' => 'Révérend Evangéliste',
                'denomination' => "Ministère d’Evangélisation Pentecotiste des Amis du Christ (MEPAC)",
                'residence' => "Pahou Bazounkpa",
                "commune" => "Ouidah",
                "contact" => "97983681",
                "owner" => 1,
            ],
            [
                'firstname' => 'GAHOUNGBOLA',
                'lastname' => 'Mouhamadou Yessoufou',
                'ministry' => 'Pasteur',
                'denomination' => "Eglise de la Rédemption Complète",
                'residence' => "Pobè Itchèko",
                "commune" => "Pobè",
                "contact" => "97051507",
                "owner" => 1,
            ],
            [
                'firstname' => 'VAGBE',
                'lastname' => 'Laurent',
                'ministry' => 'Evangéliste',
                'denomination' => "EEAD",
                'residence' => "Houèto",
                "commune" => "Abomey Calavi",
                "contact" => "52434953",
                "owner" => 1,
            ],
            [
                'firstname' => 'QUENUM',
                'lastname' => 'Gontran Sinvique',
                'ministry' => 'Pasteur',
                'denomination' => "MEBE Bénin",
                'residence' => "Kpodji",
                "commune" => "Sèmè Kpodji",
                "contact" => "90947924",
                "owner" => 1,
            ],
            [
                'firstname' => 'KPATINVOH',
                'lastname' => 'Romain Femi',
                'ministry' => 'Pasteur',
                'denomination' => "MCI",
                'residence' => "Djèrègbé",
                "commune" => "Sèmè Kpodji",
                "contact" => "67627255",
                "owner" => 1,
            ],
            [
                'firstname' => 'HOUESSINON',
                'lastname' => 'Basile',
                'ministry' => 'Pasteur',
                'denomination' => "Eglise Formatrice des Disciples du Christ (EFDC)",
                'residence' => "Houédota Djoko",
                "commune" => "Zè",
                "contact" => "97494081",
                "owner" => 1,
            ],
            [
                'firstname' => 'OJEBISI',
                'lastname' => 'Rébécca',
                'ministry' => 'Pasteur',
                'denomination' => "MCI",
                'residence' => "Djèrègbé",
                "commune" => "Sèmè Kpodji",
                "contact" => "56730884",
                "owner" => 1,
            ],
            [
                'firstname' => 'OGUME',
                'lastname' => 'Jude',
                'ministry' => 'Pasteur',
                'denomination' => "Pentecost",
                'residence' => "Niamey/Niger",
                "commune" => "Niamey",
                "contact" => "96565361",
                "owner" => 1,
            ],
            [
                'firstname' => 'ADJASSE A.',
                'lastname' => 'Irène',
                'ministry' => 'Pasteur',
                'denomination' => "MICIT",
                'residence' => "Sèmè Okoun",
                "commune" => "Sèmè Kpodji",
                "contact" => "97720316",
                "owner" => 1,
            ],
            [
                'firstname' => 'GBETIE',
                'lastname' => 'Anita',
                'ministry' => 'Prophétesse',
                'denomination' => "MICIT",
                'residence' => "Tanto",
                "commune" => "Cotonou",
                "contact" => "97572482",
                "owner" => 1,
            ],
            [
                'firstname' => 'ADJAGONOU',
                'lastname' => 'Sylvain Jesugnon',
                'ministry' => 'Pasteur',
                'denomination' => "MICIT",
                'residence' => "Djeffa",
                "commune" => "Sèmè Kpodji",
                "contact" => "97782895",
                "owner" => 1,
            ],
            [
                'firstname' => 'TOHOUEKPON',
                'lastname' => 'Sèdo Mathieu',
                'ministry' => 'Apotre',
                'denomination' => "Mission Internationale de la Paix",
                'residence' => "Djèrègbé Gbokpa",
                "commune" => "Sèmè Kpodji",
                "contact" => "96287851",
                "owner" => 1,
            ],
            [
                'firstname' => 'TOUKA',
                'lastname' => 'Akaba Tiaka T',
                'ministry' => 'Pasteur',
                'denomination' => "EMISA",
                'residence' => "Lomé",
                "commune" => "Golfe 2",
                "contact" => "+22890247200",
                "owner" => 1,
            ],
            [
                'firstname' => 'AHOUANDJINO',
                'lastname' => 'U Enock',
                'ministry' => 'Choriste',
                'denomination' => "MICIT",
                'residence' => "Sèmè Okoun",
                "commune" => "Sèmè Podji",
                "contact" => "53258557",
                "owner" => 1,
            ],
            [
                'firstname' => 'HONGA',
                'lastname' => 'Dieu donné',
                'ministry' => 'Evangéliste',
                'denomination' => "CIR",
                'residence' => "Akpakpa",
                "commune" => "Cotonou",
                "contact" => "51226508",
                "owner" => 1,
            ],
            [
                'firstname' => 'FACHOLA',
                'lastname' => 'Jean',
                'ministry' => 'Pasteur',
                'denomination' => "EEFC",
                'residence' => "Tatonnonk on",
                "commune" => "Adja Ouèrè",
                "contact" => "66441702",
                "owner" => 1,
            ],
            [
                'firstname' => 'ADJIMON',
                'lastname' => 'Sefounin',
                'ministry' => 'Evangéliste',
                'denomination' => "Eglise Internationale des Vainqueurs",
                'residence' => "Lomé Apéssito",
                "commune" => "Zio",
                "contact" => "22890911418",
                "owner" => 1,
            ],
            [
                'firstname' => 'GOUKPAM',
                'lastname' => 'Bignon',
                'ministry' => 'Evangéliste',
                'denomination' => "EPID",
                'residence' => "Pobé",
                "commune" => "Pobè",
                "contact" => "97063831",
                "owner" => 1,
            ],
            [
                'firstname' => 'WANOU',
                'lastname' => 'Timothée',
                'ministry' => 'Choriste',
                'denomination' => "Mission Internationale Cité de Triomphe (MICIT)",
                'residence' => "Akpakpa",
                "commune" => "Cotonou",
                "contact" => "61222138",
                "owner" => 1,
            ],
            [
                'firstname' => 'HOUNGU',
                'lastname' => 'Blaise',
                'ministry' => 'Pasteur',
                'denomination' => "MICIT",
                'residence' => "Acadjamey",
                "commune" => "Ouidah",
                "contact" => "96199506",
                "owner" => 1,
            ],
            [
                'firstname' => 'VAGBE',
                'lastname' => 'Laurent D',
                'ministry' => 'Evangéliste',
                'denomination' => "EEAD",
                'residence' => "Houèto",
                "commune" => "Abomey Calavi",
                "contact" => "52434953",
                "owner" => 1,
            ],
            [
                'firstname' => 'VAGBE',
                'lastname' => 'Laurent D',
                'ministry' => 'Evangéliste',
                'denomination' => "EEAD",
                'residence' => "Houèto",
                "commune" => "Abomey Calavi",
                "contact" => "52434953",
                "owner" => 1,
            ],
            [
                'firstname' => 'DOSSA M.',
                'lastname' => 'Georges',
                'ministry' => 'Serviteur de Dieu',
                'denomination' => "CAC",
                'residence' => "Calavi",
                "commune" => "Abomey Calavi",
                "contact" => "66772465",
                "owner" => 1,
            ],
            [
                'firstname' => 'HOUNTO-ADA',
                'lastname' => 'Lofanhouede Isidore',
                'ministry' => 'Apotre',
                'denomination' => "Eglise de la Puissance Irrésistible de Dieu",
                'residence' => "Bénin Zone résidentielle",
                "commune" => "Pobè",
                "contact" => "97073327",
                "owner" => 1,
            ],
            [
                'firstname' => 'KPOMASSI',
                'lastname' => 'Komi',
                'ministry' => 'Assistant évangéliste',
                'denomination' => "Eglise Jésus le Miracle",
                'residence' => "Djagble",
                "commune" => "Zio/Togo",
                "contact" => "96338398",
                "owner" => 1,
            ],
            [
                'firstname' => 'HOUSSOU',
                'lastname' => 'Floriane Melvina',
                'ministry' => 'Chantre',
                'denomination' => "Ministère Chrétien des Graces Excellentes (MCGE)",
                'residence' => "Sèmè Okoun",
                "commune" => "Sèmè Podji",
                "contact" => "63933869",
                "owner" => 1,
            ],
            [
                'firstname' => 'HOUNVENOU',
                'lastname' => 'Francine Olabissi',
                'ministry' => 'Prophétesse',
                'denomination' => "Eglise Chrétienne Racheté de Dieu (RCCG)",
                'residence' => "Calavi",
                "commune" => "Abomey Calavi",
                "contact" => "58962313",
                "owner" => 1,
            ],
            [
                'firstname' => 'HONGA',
                'lastname' => 'Omer',
                'ministry' => 'Evangéliste',
                'denomination' => "CIR",
                'residence' => "Akpakpa",
                "commune" => "Cotonou",
                "contact" => "62528100",
                "owner" => 1,
            ],
            [
                'firstname' => 'TCHEVI',
                'lastname' => 'Djimessa',
                'ministry' => 'Evangéliste',
                'denomination' => "CEFORD TOGO",
                'residence' => "Tabligbo",
                "commune" => "Yoto 1",
                "contact" => "22893491954",
                "owner" => 1,
            ],
            [
                'firstname' => 'GBEDOLO',
                'lastname' => 'Gédéon',
                'ministry' => 'Pasteur',
                'denomination' => "MICIT",
                'residence' => "Zogbadjè",
                "commune" => "Abomey Calavi",
                "contact" => "96796434",
                "owner" => 1,
            ],
            [
                'firstname' => 'KPOGNUIDE',
                'lastname' => 'Benjamin',
                'ministry' => 'Pasteur',
                'denomination' => "CEFORD TOGO",
                'residence' => "Tabligbo",
                "commune" => "Yoto 1",
                "contact" => "22899633469",
                "owner" => 1,
            ],
            [
                'firstname' => 'EBOE',
                'lastname' => 'Zinsou Nestor',
                'ministry' => 'Evangéliste',
                'denomination' => "CEFORD TOGO",
                'residence' => "Tsévié",
                "commune" => "Zio 1",
                "contact" => "22899743020",
                "owner" => 1,
            ],
            [
                'firstname' => 'AFANTCHAO',
                'lastname' => 'Christophe',
                'ministry' => 'Evangéliste',
                'denomination' => "CEFORD TOGO",
                'residence' => "Afangna",
                "commune" => "Bas Mono 1",
                "contact" => "22898325971",
                "owner" => 1,
            ],
            [
                'firstname' => 'MEDJIKO',
                'lastname' => 'Yaovi Ferdinard',
                'ministry' => 'Evangéliste',
                'denomination' => "Jésus est la Solution",
                'residence' => "Kponou",
                "commune" => "Haho 2",
                "contact" => "22897005270",
                "owner" => 1,
            ],
            [
                'firstname' => 'SADOGBE S.',
                'lastname' => 'Alphonse',
                'ministry' => 'Pasteur',
                'denomination' => "Eglise Evangélique de la Délivrance et du Salut en Christ (EEDSC)",
                'residence' => "Tankpè",
                "commune" => "Abomey Calavi",
                "contact" => "96162814",
                "owner" => 1,
            ],
            [
                'firstname' => 'HONGA',
                'lastname' => 'Dona Christiana Bénédicte',
                'ministry' => 'Evangéliste',
                'denomination' => "Communauté Internationale de la Rédemption(CIR)",
                'residence' => "Akpakpa",
                "commune" => "Cotonou",
                "contact" => "67978719",
                "owner" => 1,
            ],
            [
                'firstname' => 'AHOUANSE',
                'lastname' => 'Yasmine Isabelle',
                'ministry' => 'Evangéliste',
                'denomination' => "Mission Evangélique Pain de Vie",
                'residence' => "Goho",
                "commune" => "Abomey/Zou",
                "contact" => "97564890",
                "owner" => 1,
            ],
            [
                'firstname' => 'VLAVONOU',
                'lastname' => 'Seth Mahoutondji',
                'ministry' => 'Evangéliste',
                'denomination' => "Mission Evangélique pour la Libération des Captifs (MELC)",
                'residence' => "Djeffa Glégbonou",
                "commune" => "Sèmè Kpodji",
                "contact" => "97815532",
                "owner" => 1,
            ],
            [
                'firstname' => 'HOUNGBEDJI',
                'lastname' => 'Hermeline',
                'ministry' => 'Evangéliste et monitrice',
                'denomination' => "Cocotomey et akpakpa",
                'residence' => "Cocotomey et akpakpa",
                "commune" => "Calavi et Cotonou",
                "contact" => "98809141",
                "owner" => 1,
            ],
            [
                'firstname' => 'ALAVO',
                'lastname' => 'Gilles',
                'ministry' => 'Moniteur',
                'denomination' => "MEPA-VIE",
                'residence' => "Goho",
                "commune" => "Abomey/Zou",
                "contact" => "66059330",
                "owner" => 1,
            ],
            [
                'firstname' => 'MITCHOWANO',
                'lastname' => 'U Marius',
                'ministry' => 'Membre',
                'denomination' => "Foi Apostolique",
                'residence' => "Yagbé",
                "commune" => "Sèmè Podji",
                "contact" => "62430446",
                "owner" => 1,
            ],
            [
                'firstname' => 'MEME',
                'lastname' => 'Simon',
                'ministry' => 'Pasteur',
                'denomination' => "Eglise en Mission pour le Salut (EMS)",
                'residence' => "Godomey Togoudo",
                "commune" => "Calavi",
                "contact" => "67102077",
                "owner" => 1,
            ],
            [
                'firstname' => 'HOUNGBEDJI',
                'lastname' => 'Esther',
                'ministry' => 'Coordonnatrice des femmes et évangéliste',
                'denomination' => "Eglise Biblique de la Vie Profonde",
                'residence' => "Cité Houéyiho",
                "commune" => "Cotonou",
                "contact" => "66304145",
                "owner" => 1,
            ],
            [
                'firstname' => 'VIKPODIGNI',
                'lastname' => 'Foloashadé',
                'ministry' => 'Choriste',
                'denomination' => "Eglise Biblique de la Vie Profonde",
                'residence' => "Cité Houéyiho",
                "commune" => "Cotonou",
                "contact" => "67371356",
                "owner" => 1,
            ],
            [
                'firstname' => 'AROUNA',
                'lastname' => 'Rafatou Mondoukpè',
                'ministry' => 'Apotre/Intercesseur/Evangéliste',
                'denomination' => "Eglise Pain de Vie",
                'residence' => "",
                "commune" => "",
                "contact" => "90732509",
                "owner" => 1,
            ],
            [
                'firstname' => 'GNARIGO',
                'lastname' => 'Bénédicte',
                'ministry' => 'Chantre',
                'denomination' => "Assemblée de Dieu",
                'residence' => "Parakou",
                "commune" => "Parakou",
                "contact" => "67461564",
                "owner" => 1,
            ],
            [
                'firstname' => 'DAPA',
                'lastname' => 'Yao Hermann',
                'ministry' => 'Pasteur',
                'denomination' => "Centre de Prière Bethel",
                'residence' => "Cotonou",
                "commune" => "Cotonou",
                "contact" => "40044759",
                "owner" => 1,
            ],
            [
                'firstname' => 'NOUANTI',
                'lastname' => 'Silas',
                'ministry' => 'Pasteur',
                'denomination' => "Centre de Prière Bethel",
                'residence' => "Parakou",
                "commune" => "Borgou",
                "contact" => "66096372",
                "owner" => 1,
            ],
            [
                'firstname' => 'ADANLOKONON',
                'lastname' => 'François',
                'ministry' => 'Missionnaire',
                'denomination' => "Église Baptiste Avogbanna",
                'residence' => "Adamè",
                "commune" => "Bohicon",
                "contact" => "69622098",
                "owner" => 1,
            ],
            [
                'firstname' => 'AJAVON',
                'lastname' => 'Abraham',
                'ministry' => 'Pasteur principal',
                'denomination' => "Église Gédéon international du Togo (EGI)",
                'residence' => "Lomé",
                "commune" => "Lomé",
                "contact" => "22898939430",
                "owner" => 1,
            ],
            [
                'firstname' => 'APEDO',
                'lastname' => 'Eliakim',
                'ministry' => 'Evangéliste',
                'denomination' => "MEPES TG",
                'residence' => "Notsé",
                "commune" => "Région des plateaux",
                "contact" => "22994761024",
                "owner" => 1,
            ],
            [
                'firstname' => 'DAGONA',
                'lastname' => 'kossivi',
                'ministry' => 'Apotre',
                'denomination' => "Eglise Apostolique du Togo",
                'residence' => "Blitta",
                "commune" => "Togo",
                "contact" => "22891660614",
                "owner" => 1,
            ],
            [
                'firstname' => 'Esso',
                'lastname' => 'kodjo Gaston',
                'ministry' => 'Pasteur principal',
                'denomination' => "Ministère Impact Monde",
                'residence' => "Adéticopé",
                "commune" => "Lomé",
                "contact" => "22891640196",
                "owner" => 1,
            ],
            [
                'firstname' => 'Esso',
                'lastname' => 'Gaston',
                'ministry' => '',
                'denomination' => "NEW CITY OF GLORY DU Ministère Impact Monde",
                'residence' => "",
                "commune" => "",
                "contact" => "",
                "owner" => 1,
            ],
            [
                'firstname' => 'HOUESSOU',
                'lastname' => 'EZÉKIEL',
                'ministry' => 'Evangéliste',
                'denomination' => "MEA",
                'residence' => "Agla",
                "commune" => "Cotonou",
                "contact" => "61614229",
                "owner" => 1,
            ],
            [
                'firstname' => 'EBOE',
                'lastname' => 'ZINSOU',
                'ministry' => 'Evangéliste',
                'denomination' => "AMOUR DE DIEU",
                'residence' => "Tsévié",
                "commune" => "Lomé",
                "contact" => "22899743020",
                "owner" => 1,
            ],
            [
                'firstname' => 'MEDJILO',
                'lastname' => 'FERDINAND YAOVI',
                'ministry' => 'Evangéliste',
                'denomination' => "JÉSUS EST LA SOLUTION(JES)",
                'residence' => "Kponou",
                "commune" => "Région des plateaux",
                "contact" => "22897005270",
                "owner" => 1,
            ],
            [
                'firstname' => 'GBEMADON',
                'lastname' => 'Timothé',
                'ministry' => 'Prédicateur',
                'denomination' => "Église Apostolique du Bénin",
                'residence' => "Arafat",
                "commune" => "Parakou",
                "contact" => "69477980",
                "owner" => 1,
            ],
            [
                'firstname' => 'MALLEY',
                'lastname' => 'Anselme',
                'ministry' => 'Moniteur et choriste',
                'denomination' => "Eglise Apostolique du Bénin",
                'residence' => "Comé",
                "commune" => "Mono",
                "contact" => "96181520",
                "owner" => 1,
            ],
            [
                'firstname' => 'GANDJI',
                'lastname' => 'JACQUES DEO GRATIAS PHILIPPE',
                'ministry' => 'Evangéliste/Resp.musical/Moniteur/Prédicateur',
                'denomination' => "Mission Évangélique de la Dispensation(MED)",
                'residence' => "Ekpè",
                "commune" => "Sèmè Podji",
                "contact" => "96842189",
                "owner" => 1,
            ],
            [
                'firstname' => 'Sèhouénou',
                'lastname' => 'Clément VIKPODIGNI',
                'ministry' => 'Visionnaire',
                'denomination' => "MVCP",
                'residence' => "Houéyiho",
                "commune" => "Cotonou",
                "contact" => "64735808",
                "owner" => 1,
            ],
            [
                'firstname' => 'KOUKOUI A.',
                'lastname' => 'Alban',
                'ministry' => 'Secrétaire d’église et directeur communication',
                'denomination' => "Adventiste du Septième Jour au Bénin",
                'residence' => "3 ième arrondissement",
                "commune" => "Cotonou",
                "contact" => "97330607",
                "owner" => 1,
            ],
            [
                'firstname' => 'AGBIDINOUKOUN',
                'lastname' => 'Inès',
                'ministry' => 'Enseignante',
                'denomination' => "Vie profonde",
                'residence' => "Vedoko",
                "commune" => "Cotonou",
                "contact" => "97166779",
                "owner" => 1,
            ],
            [
                'firstname' => 'DOGLO',
                'lastname' => 'Chadrac Jesutomisin',
                'ministry' => 'Evangéliste/Assistant Pasteur',
                'denomination' => "Vie profonde",
                'residence' => "Cocotomey",
                "commune" => "Abomey Calavi",
                "contact" => "96717223",
                "owner" => 1,
            ],
            [
                'firstname' => 'DOGLO',
                'lastname' => 'Chadrac Jesutomisin',
                'ministry' => 'Evangéliste/Assistant Pasteur',
                'denomination' => "Vie profonde",
                'residence' => "Cocotomey",
                "commune" => "Abomey Calavi",
                "contact" => "96717223",
                "owner" => 1,
            ],
            [
                'firstname' => 'ANATOVI',
                'lastname' => 'JEAN-LUC',
                'ministry' => 'Chrétien',
                'denomination' => "Vie profonde",
                'residence' => "Vedoko",
                "commune" => "Littoral",
                "contact" => "95341483",
                "owner" => 1,
            ],
            [
                'firstname' => 'SADOGBE',
                'lastname' => 'S. Alphonse',
                'ministry' => 'Pasteur',
                'denomination' => "Église Évangélique de la Délivance et du Salut en Christ(Kouhounou)",
                'residence' => "Tankpè",
                "commune" => "Atlantique",
                "contact" => "96162814",
                "owner" => 1,
            ],
            [
                'firstname' => 'Tchouakpe',
                'lastname' => 'Aubierge',
                'ministry' => 'Choriste',
                'denomination' => "Oasis de Dieu",
                'residence' => "Fidjrossè",
                "commune" => "Cotonou",
                "contact" => "67208812",
                "owner" => 1,
            ],
            [
                'firstname' => 'ADANKON M.',
                'lastname' => 'Etienne',
                'ministry' => 'Pasteur',
                'denomination' => "Mission Evangélique Rehoboth International en Christ (MERIC Bénin)",
                'residence' => "PK 18",
                "commune" => "Sèmè Kpodji",
                "contact" => "97088304",
                "owner" => 1,
            ],
            [
                'firstname' => 'AGOSSOU',
                'lastname' => 'Marcellin',
                'ministry' => 'Pasteur',
                'denomination' => "MIERS Chandelier d’Or",
                'residence' => "Djèrègbé",
                "commune" => "Sèmè Kpodji",
                "contact" => "97374789",
                "owner" => 1,
            ],
            [
                'firstname' => 'ADJAI',
                'lastname' => 'Mathieu',
                'ministry' => 'Pasteur',
                'denomination' => "Mission Evangélique Interenationale du Feu de la Résurrection de Jésus Christ(MEIFRJC)",
                'residence' => "Sèmè Kraké",
                "commune" => "Sèmè Kpodji",
                "contact" => "97638538",
                "owner" => 1,
            ],
            [
                'firstname' => 'KOUTON-AKKI',
                'lastname' => 'Zéssou Roland',
                'ministry' => 'Missionnaire',
                'denomination' => "MIAV",
                'residence' => "Sèmè Kraké",
                "commune" => "Sèmè Kpodji",
                "contact" => "67465103",
                "owner" => 1,
            ],
            [
                'firstname' => 'ZANKLAN G.',
                'lastname' => 'Patrice',
                'ministry' => 'Pasteur',
                'denomination' => "Eglise Evangélique Universelle du Royaume de Dieu (EEURD)",
                'residence' => "Sado",
                "commune" => "Avrankou",
                "contact" => "62455013",
                "owner" => 1,
            ],
            [
                'firstname' => 'HOUNNOUVI',
                'lastname' => 'EKUNDAYO SAMUEL',
                'ministry' => 'EVANGELISTE',
                'denomination' => "Eglise de Dieu Universelle",
                'residence' => "OKOUN-SEME",
                "commune" => "SEME-PODJI",
                "contact" => "66720269",
                "owner" => 1,
            ],
            [
                'firstname' => 'MEME',
                'lastname' => 'Simon',
                'ministry' => 'Pasteur',
                'denomination' => "Eglise en mission pour le salut",
                'residence' => "Godomey togoudo",
                "commune" => "Calavi",
                "contact" => "67102077",
                "owner" => 1,
            ],
            [
                'firstname' => 'TAMOU',
                'lastname' => 'Myriam',
                'ministry' => 'Musulman',
                'denomination' => "Musulman",
                'residence' => "Fidjossè",
                "commune" => "Cotonou",
                "contact" => "95887026",
                "owner" => 1,
            ],
            [
                'firstname' => 'ATINDEHOU',
                'lastname' => 'Alexice',
                'ministry' => 'Pasteur',
                'denomination' => "Eglise de DIEU JJC Montagne de fortification ",
                'residence' => "Gbèdjromèdé",
                "commune" => "Cotonou",
                "contact" => "94209012",
                "owner" => 1,
            ],
            [
                'firstname' => 'TOGBDJI',
                'lastname' => 'Jacob',
                'ministry' => 'Ancien',
                'denomination' => "Eglise apostolique",
                'residence' => "Cocotomey",
                "commune" => "Calavi",
                "contact" => "95965758",
                "owner" => 1,
            ],
            [
                'firstname' => 'KAKPO',
                'lastname' => 'Mahoudo Marcelin',
                'ministry' => 'Pasteur',
                'denomination' => "ADR",
                'residence' => "Dowa",
                "commune" => "Aguegue",
                "contact" => "60080570",
                "owner" => 1,
            ],
            [
                'firstname' => 'FOLLY',
                'lastname' => 'Amavi Epiphane',
                'ministry' => 'Pasteur',
                'denomination' => "MECS",
                'residence' => "PK 10",
                "commune" => "Sèmè podji",
                "contact" => "96065695",
                "owner" => 1,
            ],
            [
                'firstname' => 'TETEVI KOKO',
                'lastname' => 'Géraldine',
                'ministry' => 'Chantre',
                'denomination' => "MISMA",
                'residence' => "TOGO Lomè",
                "commune" => "Golf",
                "contact" => "90560720",
                "owner" => 1,
            ],
            [
                'firstname' => 'OGOUBIYI',
                'lastname' => 'Théodore',
                'ministry' => 'Pasteur',
                'denomination' => "Christ le Roger",
                'residence' => "Houéyiho",
                "commune" => "Cotonou",
                "contact" => "97470420",
                "owner" => 1,
            ],
            [
                'firstname' => 'ALLOU',
                'lastname' => 'Djamilatou',
                'ministry' => 'Chantre',
                'denomination' => "UEEB",
                'residence' => "N’DALI",
                "commune" => "N’dali",
                "contact" => "67129432",
                "owner" => 1,
            ],
            [
                'firstname' => 'HONSA',
                'lastname' => 'Florent',
                'ministry' => 'Apotre',
                'denomination' => "",
                'residence' => "Djèrègbé",
                "commune" => "Seme podji",
                "contact" => "97485699",
                "owner" => 1,
            ],
            [
                'firstname' => 'HOUNGBO',
                'lastname' => 'Noé',
                'ministry' => 'EVANGELISTE',
                'denomination' => "Chapelle des vainqueurs",
                'residence' => "Seme okoun",
                "commune" => "Seme podji",
                "contact" => "66028802",
                "owner" => 1,
            ],
            [
                'firstname' => 'OLOUFOUNMI',
                'lastname' => 'Adéwalé Ulrich',
                'ministry' => 'Prophète',
                'denomination' => "MEPA VIE",
                'residence' => "G0H0",
                "commune" => "ABOMEY",
                "contact" => "65972989",
                "owner" => 1,
            ],
            [
                'firstname' => 'ZOCLI',
                'lastname' => 'Antoine',
                'ministry' => 'Ancien',
                'denomination' => "Eglise de Pentecôte Bénin ",
                'residence' => "Zogbo",
                "commune" => "Cotonou",
                "contact" => "97075833",
                "owner" => 1,
            ],
            [
                'firstname' => 'KAKESSA',
                'lastname' => 'Romance',
                'ministry' => 'Prédicatrice',
                'denomination' => "Charisma",
                'residence' => "Djeffa",
                "commune" => "Seme podji",
                "contact" => "95856258",
                "owner" => 1,
            ],
            [
                'firstname' => 'ANTONIO',
                'lastname' => 'Christelle',
                'ministry' => 'OUVRIERRE',
                'denomination' => "Vie Profonde",
                'residence' => "Porto novo",
                "commune" => "Porto novo",
                "contact" => "97900198",
                "owner" => 1,
            ],
            [
                'firstname' => 'ANTONIO',
                'lastname' => 'Cyrill',
                'ministry' => 'OUVRIER',
                'denomination' => "Vie Profonde",
                'residence' => "Porto novo",
                "commune" => "Porto novo",
                "contact" => "96127858",
                "owner" => 1,
            ],
            [
                'firstname' => 'DAKPO',
                'lastname' => 'Hernaud Louvier',
                'ministry' => 'Prophète',
                'denomination' => "Jésus- Christ est fondation",
                'residence' => "Togba",
                "commune" => "Abomey-Calavi",
                "contact" => "66644994",
                "owner" => 1,
            ],
            [
                'firstname' => 'TCHOHOUND',
                'lastname' => 'O Gisèle',
                'ministry' => 'Evangéliste',
                'denomination' => "MELAC",
                'residence' => "Minantinkpon",
                "commune" => "Ouidah",
                "contact" => "96616793",
                "owner" => 1,
            ],
            [
                'firstname' => 'TCHIBOZO',
                'lastname' => 'André',
                'ministry' => 'Pasteur',
                'denomination' => "MELAC",
                'residence' => "Minantinkpon",
                "commune" => "Ouidah",
                "contact" => "95007071",
                "owner" => 1,
            ],
            [
                'firstname' => 'SANNY',
                'lastname' => 'Wassiatou Olagnika',
                'ministry' => '',
                'denomination' => "Chapelle des vainqueurs",
                'residence' => "",
                "commune" => "",
                "contact" => "97644281",
                "owner" => 1,
            ],
            [
                'firstname' => 'LADEKPO',
                'lastname' => 'Céline',
                'ministry' => '',
                'denomination' => "",
                'residence' => "AGLA",
                "commune" => "Cotonou",
                "contact" => "95000126",
                "owner" => 1,
            ],
            [
                'firstname' => 'AHOLOU',
                'lastname' => 'Kpossi Stéphane',
                'ministry' => 'Pasteur',
                'denomination' => "Eglise Evangélique Don de Dieu",
                'residence' => "Houèzounmè",
                "commune" => "Apro-missérété",
                "contact" => "66471020",
                "owner" => 1,
            ],
            [
                'firstname' => 'N’DUWAYO',
                'lastname' => 'Sammy',
                'ministry' => 'Pasteur',
                'denomination' => "Blessing convention",
                'residence' => "BUJUMBUR A",
                "commune" => "NTAHANG WA",
                "contact" => "25769636255",
                "owner" => 1,
            ],
            [
                'firstname' => 'TODJINOU',
                'lastname' => 'Marlain',
                'ministry' => 'Pasteur',
                'denomination' => "Mission des âmes rachetées par Christ",
                'residence' => "Tori dossou somey",
                "commune" => "Tori bossito",
                "contact" => "96811277",
                "owner" => 1,
            ],
            [
                'firstname' => 'KOULONIM',
                'lastname' => 'Lalétéba Déborah',
                'ministry' => 'Evangéliste',
                'denomination' => "CEFORD TOGO",
                'residence' => "Kponou",
                "commune" => "HAHO",
                "contact" => "22897874353",
                "owner" => 1,
            ],
            [
                'firstname' => 'HOUENOU',
                'lastname' => 'Bruno',
                'ministry' => 'Apotre',
                'denomination' => "MCAV",
                'residence' => "Calavi",
                "commune" => "Calavi",
                "contact" => "97643248",
                "owner" => 1,
            ],
            [
                'firstname' => 'AGBO',
                'lastname' => 'Sylvie',
                'ministry' => 'Monitrice',
                'denomination' => "Mission Evangélique Pain de Vie",
                'residence' => "DOKPA",
                "commune" => "Abomey",
                "contact" => "90673231",
                "owner" => 1,
            ],
            [
                'firstname' => 'DEDEWANOU',
                'lastname' => 'J. Claude',
                'ministry' => 'Evangéliste',
                'denomination' => "ENAAC",
                'residence' => "Malé",
                "commune" => "Avrankou",
                "contact" => "62196752",
                "owner" => 1,
            ],
            [
                'firstname' => 'HOUSSOU',
                'lastname' => 'Odette',
                'ministry' => 'Pasteur',
                'denomination' => "MCGE",
                'residence' => "Sèmè okoun",
                "commune" => "Sèmè Podji",
                "contact" => "62196752",
                "owner" => 1,
            ],
            [
                'firstname' => 'ADEYI',
                'lastname' => 'Euloge',
                'ministry' => 'APOTRE',
                'denomination' => "AJC",
                'residence' => "Djègandaho",
                "commune" => "Porto-novo",
                "contact" => "97148953",
                "owner" => 1,
            ],
            [
                'firstname' => 'HOUEDANOU',
                'lastname' => 'Elise',
                'ministry' => 'APOTRE',
                'denomination' => "La Nouvelle Jérusalem",
                'residence' => "LOKOSSA",
                "commune" => "",
                "contact" => "95559364",
                "owner" => 1,
            ],
            [
                'firstname' => 'TOGBE SOSSA',
                'lastname' => 'Gérard',
                'ministry' => 'Prophète',
                'denomination' => "MIPSEA",
                'residence' => "Porto novo",
                "commune" => "Porto novo",
                "contact" => "97737041",
                "owner" => 1,
            ],
            [
                'firstname' => 'DEGBE ABAGNON',
                'lastname' => 'Ignace',
                'ministry' => 'Pasteur',
                'denomination' => "Miel",
                'residence' => "Djègan-daho",
                "commune" => "Porto novo",
                "contact" => "96466252",
                "owner" => 1,
            ],
            [
                'firstname' => 'ADEYEMI Dourodjaye',
                'lastname' => 'Clarisse',
                'ministry' => 'Pasteur',
                'denomination' => "Eglise évangélque des apotres du Christ",
                'residence' => "Ketou",
                "commune" => "Ketou",
                "contact" => "96820890",
                "owner" => 1,
            ],
            [
                'firstname' => 'ASSOGBA',
                'lastname' => 'Paul',
                'ministry' => 'Enseignante',
                'denomination' => "MEPPSE",
                'residence' => "Cotonou",
                "commune" => "Cotonou",
                "contact" => "97889132",
                "owner" => 1,
            ],
            [
                'firstname' => 'DOSSOU',
                'lastname' => 'Antoine',
                'ministry' => 'Pasteur',
                'denomination' => "Ministère international",
                'residence' => "Houedo",
                "commune" => "Calavi",
                "contact" => "66451623",
                "owner" => 1,
            ],

            // JE M'ARRETE LA D'ABORD à l'ID :126
        ];
        foreach ($repertoires as $repertoire) {
            \App\Models\Repertory::factory()->create($repertoire);
        };
    }
}
